 export const picList=[
    {
      id:1,
      url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR6_LT0pAiGNxPsiop0vaytbYiEsUlHJyisg&usqp=CAU"
    },
    {
      id:2,
      url:"https://icons.iconarchive.com/icons/martz90/circle/512/calendar-icon.png"
    },
    {
      id:3,
      url:"https://cdn1.iconfinder.com/data/icons/social-messaging-ui-color-shapes/128/target-circle-blue-512.png"
    },
    {
      id:4,
      url:"https://www.seekpng.com/png/small/428-4287240_no-avatar-user-circle-icon-png.png"
    },
    {
      id:5,
      url:"https://www.shareicon.net/data/512x512/2015/11/13/671456_star_512x512.png"
    }
  ]